### ISSUE TITLE
Resolve Vulkan location and structure

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#1018]
### Describe the feature

If we continue to use Vulkan, we should move https://github.com/goki/vulkan somewhere into the Cogent Core space, try again to merge it upstream, or use a better Vulkan package. We may also use WebGPU instead (see #507).

**Comment by theclapp** [comment]
While you're at it, it might (or, of course, might not) be useful to look at some of the other forks of vulkan-go/vulkan (https://github.com/vulkan-go/vulkan/network) for useful code and/or bug fixes. And perhaps even some of their open PRs.

I mention this in part because I ran into a bug in a library I'd forked, and committed a fix, and went to upstream, only to see that they had an unmerged PR to fix the same issue that was *two years old*. So I was bitter about that, but my point is sometimes there's useful code in other people's forks and/or PRs.

Apologies if you've already thought of all that. :)

**Comment by kkoreilly** [comment]
Thank you for the suggestion! I think we already merged any other useful forks into our fork in addition to the improvements we made ourselves. Regardless, we are planning to migrate to WebGPU now (#507), so hopefully all of these issues will become irrelevant.

**Comment by rcoreilly** [comment]
I didn't know about that /network feature!  very handy.
