### ISSUE TITLE
fileinfo, filetree, and Cogent Code should properly identify, treat generated files.

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#1238]
### Describe the feature

per https://github.com/golang/go/issues/13560 generated files are identified by a standard comment.  `fileinfo` should check for this comment in .go files and set a "Generated" flag. Then filetree can style such files with an appropriate lighter text color (we use this for non-vcs files -- probably just re-use same and you can look at the file info to see which is which). Finally, Cogent Code will open such files with the texteditor set to read only, unless you open using the `Edit` filetree command.

**Comment by kkoreilly** [comment]
To me it seems a little risky to use the same indicator for generated files and untracked files, since one of the main use cases of such an indicator would be to determine if a generated file is erroneously checked in or not checked in depending on your intention. "Look at the file info" is not really a great solution.

**Comment by rcoreilly** [comment]
Yeah, suggestion for appropriate distinct styling?

**Comment by kkoreilly** [comment]
Some kind of icon? Or just some other text color such as yellow?

**Comment by rcoreilly** [comment]
this is all implemented within the goal pr where it is essential.
