### ISSUE TITLE
Margin is still getting events

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#773]

**Comment by rcoreilly** [comment]
Benefits:
* Splitter and other handles
* in general larger touch targets on mobile (could change stying to make bigger still)

Cons:
* Close button on tabs, which can easily be solved by using a space instead of margin, like it used to be.

If Kai can get over his unexplained allergy of the Space and Stretch elements, it seems obvious that this is a net win all around.

**Comment by kkoreilly** [comment]
Cons: major violation of the CSS spec, end-user and programmer expectations, and event handling consistency.

**Comment by kkoreilly** [comment]
We have decided to have margin continue to receive events, as that makes more logical sense and makes splits and other elements work more elegantly and effectively, especially on mobile. The issues with close buttons on tabs have been resolved by using Space elements, as stated in #581.
